[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[tool.pytest.ini_options]
pythonpath = ["."]

[tool.black]
line-length = 88
target-version = ["py311"]
extend-exclude = "alembic/"

[tool.isort]
profile = "black"
line_length = 88
skip = [".venv", "alembic", "__pycache__"]
