"""seat_holds_window_minutes not null

Revision ID: aa86f1f4a997
Revises: d3e9a1f5b274
Create Date: 2026-07-02 17:08:40.329373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa86f1f4a997'
down_revision: Union[str, Sequence[str], None] = 'd3e9a1f5b274'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_log_actor'), table_name='audit_log')
    op.create_index(op.f('ix_audit_log_actor_user_id'), 'audit_log', ['actor_user_id'], unique=False)
    # Backfill NULLs before enforcing NOT NULL — the column was originally
    # created nullable with a server default of 10, so pre-existing rows may
    # have NULL if the default was never applied at the application level.
    op.execute(
        "UPDATE events SET seat_holds_window_minutes = 10 "
        "WHERE seat_holds_window_minutes IS NULL"
    )
    op.alter_column('events', 'seat_holds_window_minutes',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('10'))
    op.drop_index(op.f('ix_events_organizer'), table_name='events')
    op.drop_index(op.f('ix_events_status'), table_name='events')
    op.create_index(op.f('ix_events_organizer_id'), 'events', ['organizer_id'], unique=False)
    op.drop_index(op.f('ix_admin_comments_organizer'), table_name='organizer_admin_comments')
    op.create_index(op.f('ix_organizer_admin_comments_organizer_id'), 'organizer_admin_comments', ['organizer_id'], unique=False)
    op.drop_index(op.f('ix_org_documents_organizer'), table_name='organizer_documents')
    op.create_index(op.f('ix_organizer_documents_organizer_id'), 'organizer_documents', ['organizer_id'], unique=False)
    op.drop_index(op.f('ix_organizers_slug'), table_name='organizers')
    op.drop_index(op.f('ix_organizers_user_id'), table_name='organizers')
    op.drop_constraint(op.f('season_pass_purchases_purchase_token_key'), 'season_pass_purchases', type_='unique')
    op.drop_index(op.f('ix_season_pass_purchases_purchase_token'), table_name='season_pass_purchases')
    op.create_index(op.f('ix_season_pass_purchases_purchase_token'), 'season_pass_purchases', ['purchase_token'], unique=True)
    op.drop_index(op.f('ix_season_pass_redemptions_purchase_id'), table_name='season_pass_redemptions')
    op.create_index(op.f('ix_season_pass_redemptions_season_pass_purchase_id'), 'season_pass_redemptions', ['season_pass_purchase_id'], unique=False)
    op.drop_index(op.f('uq_seat_holds_active'), table_name='seat_holds', postgresql_where="((status)::text = 'held'::text)")
    op.drop_constraint(op.f('subscription_plans_code_key'), 'subscription_plans', type_='unique')
    op.drop_index(op.f('ix_subscription_plans_code'), table_name='subscription_plans')
    op.create_index(op.f('ix_subscription_plans_code'), 'subscription_plans', ['code'], unique=True)
    op.create_foreign_key(None, 'ticket_orders', 'event_functions', ['function_id'], ['id'])
    op.drop_index(op.f('ix_ticket_types_event'), table_name='ticket_types')
    op.create_index(op.f('ix_ticket_types_event_id'), 'ticket_types', ['event_id'], unique=False)
    op.create_foreign_key(None, 'tickets', 'event_functions', ['function_id'], ['id'])
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_venues_organizer'), table_name='venues')
    op.create_index(op.f('ix_venues_organizer_id'), 'venues', ['organizer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_venues_organizer_id'), table_name='venues')
    op.create_index(op.f('ix_venues_organizer'), 'venues', ['organizer_id'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_index(op.f('ix_ticket_types_event_id'), table_name='ticket_types')
    op.create_index(op.f('ix_ticket_types_event'), 'ticket_types', ['event_id'], unique=False)
    op.drop_constraint(None, 'ticket_orders', type_='foreignkey')
    op.drop_index(op.f('ix_subscription_plans_code'), table_name='subscription_plans')
    op.create_index(op.f('ix_subscription_plans_code'), 'subscription_plans', ['code'], unique=False)
    op.create_unique_constraint(op.f('subscription_plans_code_key'), 'subscription_plans', ['code'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('uq_seat_holds_active'), 'seat_holds', ['event_id', 'function_id', 'seat_id'], unique=True, postgresql_where="((status)::text = 'held'::text)")
    op.drop_index(op.f('ix_season_pass_redemptions_season_pass_purchase_id'), table_name='season_pass_redemptions')
    op.create_index(op.f('ix_season_pass_redemptions_purchase_id'), 'season_pass_redemptions', ['season_pass_purchase_id'], unique=False)
    op.drop_index(op.f('ix_season_pass_purchases_purchase_token'), table_name='season_pass_purchases')
    op.create_index(op.f('ix_season_pass_purchases_purchase_token'), 'season_pass_purchases', ['purchase_token'], unique=False)
    op.create_unique_constraint(op.f('season_pass_purchases_purchase_token_key'), 'season_pass_purchases', ['purchase_token'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_organizers_user_id'), 'organizers', ['user_id'], unique=False)
    op.create_index(op.f('ix_organizers_slug'), 'organizers', ['slug'], unique=False)
    op.drop_index(op.f('ix_organizer_documents_organizer_id'), table_name='organizer_documents')
    op.create_index(op.f('ix_org_documents_organizer'), 'organizer_documents', ['organizer_id'], unique=False)
    op.drop_index(op.f('ix_organizer_admin_comments_organizer_id'), table_name='organizer_admin_comments')
    op.create_index(op.f('ix_admin_comments_organizer'), 'organizer_admin_comments', ['organizer_id'], unique=False)
    op.drop_index(op.f('ix_events_organizer_id'), table_name='events')
    op.create_index(op.f('ix_events_status'), 'events', ['status'], unique=False)
    op.create_index(op.f('ix_events_organizer'), 'events', ['organizer_id'], unique=False)
    op.alter_column('events', 'seat_holds_window_minutes',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('10'))
    op.drop_index(op.f('ix_audit_log_actor_user_id'), table_name='audit_log')
    op.create_index(op.f('ix_audit_log_actor'), 'audit_log', ['actor_user_id'], unique=False)
    # ### end Alembic commands ###
